USE [master]
GO
CREATE DATABASE [ByCodersTec]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ByCodersTec', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ByCodersTec.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ByCodersTec_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ByCodersTec_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ByCodersTec] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ByCodersTec].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ByCodersTec] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ByCodersTec] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ByCodersTec] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ByCodersTec] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ByCodersTec] SET ARITHABORT OFF 
GO
ALTER DATABASE [ByCodersTec] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ByCodersTec] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ByCodersTec] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ByCodersTec] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ByCodersTec] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ByCodersTec] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ByCodersTec] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ByCodersTec] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ByCodersTec] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ByCodersTec] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ByCodersTec] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ByCodersTec] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ByCodersTec] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ByCodersTec] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ByCodersTec] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ByCodersTec] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ByCodersTec] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ByCodersTec] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ByCodersTec] SET  MULTI_USER 
GO
ALTER DATABASE [ByCodersTec] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ByCodersTec] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ByCodersTec] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ByCodersTec] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ByCodersTec] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ByCodersTec] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ByCodersTec] SET QUERY_STORE = ON
GO
ALTER DATABASE [ByCodersTec] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ByCodersTec]
GO
/****** Object:  Table [dbo].[ImportFiles]    Script Date: 10/29/2025 3:49:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImportFiles](
	[Id] [uniqueidentifier] NOT NULL,
	[ImportDate] [datetime] NOT NULL,
	[FileName] [varchar](200) NOT NULL,
	[UserId] [varchar](50) NULL,
	[TotalRows] [int] NOT NULL,
	[ImportedRows] [int] NOT NULL,
 CONSTRAINT [PK_ImportedFiles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[Id] [uniqueidentifier] NOT NULL,
	[ImportFileId] [uniqueidentifier] NOT NULL,
	[TransactionTypeId] [int] NOT NULL,
	[OccurrenceDate] [datetime] NOT NULL,
	[Value] [decimal](18, 2) NOT NULL,
	[Cpf] [varchar](11) NOT NULL,
	[Card] [varchar](12) NOT NULL,
	[StoreOwner] [varchar](14) NOT NULL,
	[StoreName] [varchar](19) NOT NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TransactionTypes](
	[Id] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Nature] [varchar](50) NOT NULL,
	[Sign] [char](1) NOT NULL,
 CONSTRAINT [PK_TransactionTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_Transactions_StoreName] ON [dbo].[Transactions]
(
	[StoreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_ImportFiles] FOREIGN KEY([ImportFileId])
REFERENCES [dbo].[ImportFiles] ([Id])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_ImportFiles]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_TransactionTypes] FOREIGN KEY([TransactionTypeId])
REFERENCES [dbo].[TransactionTypes] ([Id])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_TransactionTypes]
GO
USE [master]
GO
ALTER DATABASE [ByCodersTec] SET  READ_WRITE 
GO